dist: xenial
sudo: true
services:
  - docker
language: python
python:
  - "3.7"
before_install:
  - touch .env
  - cd environments/test/
  - docker-compose build tests-runner
script:
  - docker-compose run --rm --entrypoint coverage tests-runner run -m pytest
after_success:
  - cd ../..
  - codecov
