version: "3"
services:

  #####################
  ###  Django app   ###
  #####################
  django-app:
    build:
      context: ../..
      dockerfile: environments/dev/BackendDockerfile
      args:
        REQUIREMENTS: requirements/requirements-dev.txt
    env_file: ../../.env
    environment:
      - PYTHONIOENCODING=UTF-8
      - PYTHONUNBUFFERED=1
    volumes:
      - "../../:/code"
    depends_on:
      - postgres-db
    ports:
      - "80:80"
    command: python /code/manage.py runserver 0.0.0.0:80

  #####################
  ####  Database   ####
  #####################
  postgres-db:
    image: postgres:12
    restart: always
    env_file: ../../.env
    volumes:
      - ~/Dropbox/projects/blog:/data
      - blog-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  #####################
  ###  Svelte app   ###
  #####################
  svelte-app:
    build:
      context: .
      dockerfile: FrontendDockerfile
    volumes:
      - "../../blog/static/:/code"
    command: npm run dev

  #####################
  ####   Mailhog   ####
  #####################
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI

  #####################
  #####   Ngrok   #####
  #####################
  ngrok:
    image: wernight/ngrok
    links:
      - django-app
    command: ngrok http django-app:80
    ports:
      - "4040:4040" # Access to public domain: /api/tunnels

  #####################
  ### Tests runner  ###
  #####################
  tests-runner:
    build:
      context: ../..
      dockerfile: environments/test/Dockerfile
      args:
        REQUIREMENTS: requirements/requirements-test.txt
    env_file: ../../.env
    volumes:
      - "../../:/code"

volumes:
  blog-data: {}
